### ISSUE TITLE
tvb-matlab wrong/missing reference, clone fails

### ISSUE THREAD

**Issue by danielberlin** [the-virtual-brain/tvb-pack#6]
https://github.com/the-virtual-brain/tvb-matlab seems to not exist anymore. However, it is referenced by tvb-pack/matlab and thus cloning fails for me.

**Comment by maedoc** [comment]
@danielberlin good catch; we recently removed the tvb-matlab repo (old and not functional) and forgot to remove the reference from tvb-pack.

Can you please retry?

**Comment by danielberlin** [comment]
Working now.
