### ISSUE TITLE
tvb data failed to check out

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-pack#8]
Did the standard thing: git submodule init, git submodule update

Made no change to the tvb-data ref in .gitmodule, but still getting the error

fatal: reference is not a tree: 1d6893f6f9c5d0e8b50b63dd8b63a5ccb55105b3
Unable to checkout '1d6893f6f9c5d0e8b50b63dd8b63a5ccb55105b3' in submodule path 'tvb-data'

**Comment by maedoc** [comment]
We're still working on a workaround since our data repo exceeds GitHub's limits. 

In the meantime, you're better off grabbing this from the SVN.

**Comment by liadomide** [comment]
John, could you try again now ?
