### ISSUE TITLE
Unable to manage packages with pip

### ISSUE THREAD

**Issue by mattja** [the-virtual-brain/tvb-pack#9]
It seems that tvb-library and tvb-framework are python packages with different content, 
but their setup.py files both have `name = 'tvb'` giving a name clash.

Installing editable with `pip install -e .` in tvb-library/ also fails for me, with error:
`No files/directories in /home/user2/py/tvb-pack/tvb-library (from PKG-INFO)`

Before I look further into fixing these issues I would like to understand better why tvb is 
structured in this way.

Using standard python package conventions would make it easier for me to make tvb-library and
tvb-framework available to colleagues like other python libraries.

**Comment by maedoc** [comment]
The framework depends on the library, so we intend for the library to be used by itself or to have both installed.

Unless you plan to use the web app and run a database, you probably just need to make the library and data package (whose top level name is tvb_data) available.

**Comment by liadomide** [comment]
After recent work, you can find tvb-data, tvb-gdist, tvb-library and tvb-framework on Pypi.
